version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    env_file:
      - .env
    # environment:
    #   NODE_ENV: development
    volumes:
      - app-data:/usr/src/app
    command: npm start

volumes:
  app-data:
